---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>

name: nargothrond
description: This is my personal OS image with proprietary NVIDIA drivers.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42  # Or "latest"

# Module configuration, executed in order. Multiple instances of the same module is permitted.

modules:
  - from-file: 10-akmods.yml
  - from-file: 20-packages.yml
  - from-file: 30-files.yml
  - from-file: 40-scripts.yml
  - from-file: 50-flatpaks.yml
  - from-file: 60-systemd.yml
  - from-file: 70-gnome-extensions.yml
  - from-file: 80-gnome-settings.yml
  - from-file: 90-cleanup.yml

  - type: signing # Necessary for signing files
