# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>

name: nargothrond
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43  # Or "latest"

# Module configuration, executed in order. Multiple instances of the same module is permitted.

modules:
  - from-file: common.yml
