---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: nargothrond
# description will be included in the image's metadata
description: This is my personal OS image with nvidia drivers.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: script
    scripts:
      - papirus/icons-setup.sh
      - papirus/folders-setup.sh
      - papirus/theme-setup.sh
      - nvidia/nvidia-setup.sh
      - autofirma/autofirma-setup.sh
      - repos/disable-repos.sh

  - from-file: pkgs/files.yml
  - type: files
    files:
      - source: system/dev/starship-profile
        destination: /etc/profile.d/

  - from-file: pkgs/rpms.yml
  - from-file: pkgs/flatpaks.yml
  - from-file: pkgs/extensions.yml

  - type: gschema-overrides
    include:
      - zz1.settings.gschema.override
      - zz2.extensions.gschema.override

  - type: systemd
    system:
      enabled:
        - bootc-fetch-apply-updates.timer
        - tailscaled.service
        - intel-undervolt.service
      disabled:
        - NetworkManager-wait-online.service
        - rpm-ostreed-automatic.timer
        
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
