---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>

name: nargothrond
description: This is my personal OS image with proprietary NVIDIA drivers.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42  # Or "latest"

# Module configuration, executed in order. Multiple instances of the same module is permitted.

modules:
  - from-file: akmods.yml
  - from-file: files.yml
  - from-file: dnf.yml
  - from-file: script.yml
  - from-file: default-flatpaks.yml
  - from-file: gnome-extensions.yml
  - from-file: gschema-overrides.yml
  - from-file: justfiles.yml

  - type: signing # Necessary for signing files
